/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make direct changes to this file.

import { createFileRoute as createFileRoute_byId } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as ProductsCreateImport } from './routes/products/create'
import { Route as ProductsIdImport } from './routes/products/$id'
import { Route as ProductsIdEditImport } from './routes/products/$id_.edit'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProductsIndexRoute = ProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsCreateRoute = ProductsCreateImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIdRoute = ProductsIdImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIdEditRoute = ProductsIdEditImport.update({
  id: '/products/$id_/edit',
  path: '/products/$id/edit',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/create': {
      id: '/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof ProductsCreateImport
      parentRoute: typeof rootRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdImport
      parentRoute: typeof rootRoute
    }
    '/products/$id_/edit': {
      id: '/products/$id_/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof ProductsIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/create': typeof ProductsCreateRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/create': typeof ProductsCreateRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/create': typeof ProductsCreateRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/$id_/edit': typeof ProductsIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products' | '/products/create' | '/products/$id' | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products' | '/products/create' | '/products/$id' | '/products/$id/edit'
  id: '__root__' | '/' | '/products/' | '/products/create' | '/products/$id' | '/products/$id_/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsCreateRoute: typeof ProductsCreateRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIdEditRoute: typeof ProductsIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsCreateRoute: ProductsCreateRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsIdEditRoute: ProductsIdEditRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
